; Production settings
upload_max_filesize = 5M
post_max_size = 5M
display_errors = Off
log_errors = On
;; EXTENSION
extension=curl
extension=ftp
extension=fileinfo
extension=gettext
extension=intl
extension=mbstring
extension=mysqli
extension=openssl
extension=pdo_mysql
extension=pdo_sqlite

extension=sockets
;extension=sqlite3
extension=zip